version: 2
models:
  - name: core__fact_traces
    description: '{{ doc("eth_traces_table_doc") }}'  

    columns:
      - name: BLOCK_NUMBER
        description: '{{ doc("eth_traces_block_no") }}'   
      - name: BLOCK_TIMESTAMP
        description: '{{ doc("eth_traces_blocktime") }}'
      - name: TX_HASH
        description: '{{ doc("eth_traces_tx_hash") }}' 
      - name: FROM_ADDRESS
        description: '{{ doc("eth_traces_from") }}'
      - name: TO_ADDRESS
        description: '{{ doc("eth_traces_to") }}'
      - name: ETH_VALUE
        description: '{{ doc("eth_traces_eth_value") }}'
      - name: ETH_VALUE_PRECISE_RAW
        description: '{{ doc("precise_amount_unadjusted") }}'
      - name: ETH_VALUE_PRECISE
        description: '{{ doc("precise_amount_adjusted") }}'
      - name: GAS
        description: '{{ doc("eth_traces_gas") }}'
      - name: GAS_USED
        description: '{{ doc("eth_traces_gas_used") }}'
      - name: INPUT
        description: '{{ doc("eth_traces_input") }}'
      - name: OUTPUT
        description: '{{ doc("eth_traces_output") }}'
      - name: TYPE
        description: '{{ doc("eth_traces_type") }}'
      - name: IDENTIFIER
        description: '{{ doc("eth_traces_identifier") }}'
      - name: DATA
        description: '{{ doc("eth_traces_call_data") }}'
      - name: TX_STATUS
        description: '{{ doc("eth_tx_status") }}' 
      - name: SUB_TRACES
        description: '{{ doc("eth_traces_sub") }}' 
      - name: TRACE_STATUS
        description: The status of the trace, either `SUCCESS` or `FAIL`
      - name: ERROR_REASON
        description: The reason for the trace failure, if any.
      - name: TRACE_INDEX
        description: The index of the trace within the transaction.        